function [imdsTrain, imdsValidation] = loadData(folderDataName)
    % Load training and validation data from the specified folder
    imdsTrain = imageDatastore(fullfile(folderDataName, 'Train'), ...
        'IncludeSubfolders', true, ...
        'FileExtensions', [".jpg", ".png"], ...
        'LabelSource', 'foldernames');

    imdsValidation = imageDatastore(fullfile(folderDataName, 'Test'), ...
        'IncludeSubfolders', true, ...
        'FileExtensions', [".jpg", ".png"], ...
        'LabelSource', 'foldernames');
end
