function [imdsTrain, imdsTest, imdsValidation] = loadData(folderDataName)
    % Load training and validation data from the specified folder
    imdsTrain = imageDatastore(fullfile(folderDataName, 'Train'), ...
        'IncludeSubfolders', true, ...
        'FileExtensions', [".jpg", ".png"], ...
        'LabelSource', 'foldernames');

    imdsTest = imageDatastore(fullfile(folderDataName, 'Test'), ...
        'IncludeSubfolders', true, ...
        'FileExtensions', [".jpg", ".png"], ...
        'LabelSource', 'foldernames');
    
    validationFolderPath = fullfile(folderDataName, 'Validation');

    if exist(validationFolderPath, 'dir')
        imdsValidation = imageDatastore(validationFolderPath, ...
            'IncludeSubfolders', true, ...
            'FileExtensions', [".jpg", ".png"], ...
            'LabelSource', 'foldernames');
    else
        imdsValidation = imdsTrain;
    end
end
